package org.noos.xing.mydoggy.plaf.ui;

/**
 * @author Angelo De Caro (angelo.decaro@gmail.com)
 */
public interface MyDoggyKeySpace {

    // Icons

    String DOCKED = "DOCKED";
    String DOCKED_INACTIVE = "DOCKED_INACTIVE";
    String SLIDING = "SLIDING";
    String SLIDING_INACTIVE = "SLIDING_INACTIVE";
    String FLOATING = "FLOATING";
    String FLOATING_INACTIVE = "FLOATING_INACTIVE";
    String FIX = "FIX";
    String FIX_INACTIVE = "FIX_INACTIVE";
    String AUTO_HIDE_ON = "AUTO_HIDE_ON";
    String AUTO_HIDE_ON_INACTIVE = "AUTO_HIDE_ON_INACTIVE";
    String AUTO_HIDE_OFF = "AUTO_HIDE_OFF";
    String AUTO_HIDE_OFF_INACTIVE = "AUTO_HIDE_OFF_INACTIVE";
    String HIDE_TOOL_WINDOW = "HIDE_TOOL_WINDOW";
    String HIDE_TOOL_WINDOW_INACTIVE = "HIDE_TOOL_WINDOW_INACTIVE";
    String MAXIMIZE = "MAXIMIZE";
    String MAXIMIZE_INACTIVE = "MAXIMIZE_INACTIVE";
    String MINIMIZE = "MINIMIZE";
    String MINIMIZE_INACTIVE = "MINIMIZE_INACTIVE";
    String ACTIONS_POPUP = "ACTIONS_POPUP";
    String ACTIONS_POPUP_INACTIVE = "ACTIONS_POPUP_INACTIVE";

    String TOO_WINDOW_TAB_POPUP = "TOO_WINDOW_TAB_POPUP";

    String CONTENT_PAGE_DETACH = "CONTENT_PAGE_DETACH";
    String CONTENT_PAGE_CLOSE = "CONTENT_PAGE_CLOSE";
    String CONTENT_PAGE_DETACH_INACTIVE = "CONTENT_PAGE_DETACH_INACTIVE";
    String CONTENT_PAGE_CLOSE_INACTIVE = "CONTENT_PAGE_CLOSE_INACTIVE";

    String TOOL_SCROLL_BAR_UP = "TOOL_SCROLL_BAR_UP";
    String TOOL_SCROLL_BAR_DOWN = "TOOL_SCROLL_BAR_DOWN";
    String TOOL_SCROLL_BAR_LEFT = "TOOL_SCROLL_BAR_LEFT";
    String TOOL_SCROLL_BAR_RIGHT = "TOOL_SCROLL_BAR_RIGHT";

    String TAB_CLOSE = "TAB_CLOSE";
    String TAB_CLOSE_INACTIVE = "TAB_CLOSE_INACTIVE"; 

    // Representative Anchor Button - Colors

    String TOOL_SCROLL_BAR_UI_BCK_START = "TOOL_SCROLL_BAR_UI_BCK_START";
    String TOOL_SCROLL_BAR_UI_BCK_END = "TOOL_SCROLL_BAR_UI_BCK_END";

    String RAB_MOUSE_IN_BORDER = "RAB_MOUSE_IN_BORDER";
    String RAB_MOUSE_OUT_BORDER = "RAB_MOUSE_OUT_BORDER";
    String RAB_BACKGROUND_INACTIVE = "RAB_BACKGROUND_INACTIVE";
    String RAB_BACKGROUND_ACTIVE_START = "RAB_BACKGROUND_ACTIVE_START";
    String RAB_BACKGROUND_ACTIVE_END = "RAB_BACKGROUND_ACTIVE_END";
    String RAB_FOREGROUND = "RAB_FOREGROUND";
    String RAB_FOREGROUND_NOT_AVAILABLE = "RAB_FOREGROUND_NOT_AVAILABLE";

    // ToolWindow TitleBar - Colors

    String TWTB_BACKGROUND_ACTIVE_START = "TWTB_BACKGROUND_ACTIVE_START";
    String TWTB_BACKGROUND_ACTIVE_END = "TWTB_BACKGROUND_ACTIVE_END";
    String TWTB_BACKGROUND_INACTIVE_START = "TWTB_BACKGROUND_INACTIVE_START";
    String TWTB_BACKGROUND_INACTIVE_END = "TWTB_BACKGROUND_INACTIVE_END";

    String TWTB_ID_BACKGROUND_FLASHING_0 = "TWTB_ID_BACKGROUND_FLASHING_0";
    String TWTB_ID_BACKGROUND_FLASHING_1 = "TWTB_ID_BACKGROUND_FLASHING_1";
    String TWTB_ID_BACKGROUND_ANIMATING = "TWTB_ID_BACKGROUND_ANIMATING";
    String TWTB_ID_BACKGROUND_ACTIVE = "TWTB_ID_BACKGROUND_ACTIVE";
    String TWTB_ID_BACKGROUND_INACTIVE = "TWTB_ID_BACKGROUND_INACTIVE";
    String TWTB_ID_FOREGROUND_ACTIVE = "TWTB_ID_FOREGROUND_ACTIVE";
    String TWTB_ID_FOREGROUND_INACTIVE = "TWTB_ID_FOREGROUND_INACTIVE";

    String TWTB_TAB_FOREGROUND_SELECTED = "TWTB_TAB_FOREGROUND_SELECTED";
    String TWTB_TAB_FOREGROUND_UNSELECTED = "TWTB_TAB_FOREGROUND_UNSELECTED";

    // Components, ComponentsUIs, Customizers

    String TOOL_WINDOW_CONTAINER = "TOOL_WINDOW_CONTAINER";
    String TOOL_WINDOW_TITLE_BAR = "TOOL_WINDOW_TITLE_BAR";
    String TOOL_WINDOW_TITLE_BAR_UI = "TOOL_WINDOW_TITLE_BAR_UI";
    String TOOL_WINDOW_TITLE_BUTTON = "TOOL_WINDOW_TITLE_BUTTON";

    String REPRESENTATIVE_ANCHOR_BUTTON_UI = "REPRESENTATIVE_ANCHOR_BUTTON_UI";

    String TOOL_WINDOW_MANAGER = "TOOL_WINDOW_MANAGER";
    String TOOL_WINDOW_MANAGER_CONTENT_CONTAINER = "TOOL_WINDOW_MANAGER_CONTENT_CONTAINER";

    String TOOL_SCROLL_BAR_ARROW = "TOOL_SCROLL_BAR_ARROW";

    String ANCHOR_SPLIT_PANE = "ANCHOR_SPLIT_PANE";
    String ANCHOR_CONTENT_PANE = "ANCHOR_CONTENT_PANE";

    String CORNER_CONTENT_PANE = "CORNER_CONTENT_PANE";
    String DESKTOP_CONTENT_PANE = "DESKTOP_CONTENT_PANE";

    String MULTI_SPLIT_CONTAINER_SPLIT = "MULTI_SPLIT_CONTAINER_SPLIT";
}
