/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_noos_xing_mydoggy_plaf_ui_transparency_TransparencyManager */

#ifndef _Included_org_noos_xing_mydoggy_plaf_ui_transparency_TransparencyManager
#define _Included_org_noos_xing_mydoggy_plaf_ui_transparency_TransparencyManager
#ifdef __cplusplus
extern "C" {
#endif

	/*
 * Class:     org_noos_xing_mydoggy_plaf_ui_transparency_TransparencyManager
 * Method:    isAlphaModeEnabledWin32Impl
 * Signature: (Ljava/awt/Window;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_noos_xing_mydoggy_plaf_ui_transparency_TransparencyManager_isAlphaModeEnabledWin32Impl
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_noos_xing_mydoggy_plaf_ui_transparency_TransparencyManager
 * Method:    setAlphaModeEnabledWin32Impl
 * Signature: (Ljava/awt/Window;Z)V
 */
JNIEXPORT void JNICALL Java_org_noos_xing_mydoggy_plaf_ui_transparency_TransparencyManager_setAlphaModeEnabledWin32Impl
  (JNIEnv *, jclass, jobject, jboolean);

/*
 * Class:     org_noos_xing_mydoggy_plaf_ui_transparency_TransparencyManager
 * Method:    setAlphaModeRatioWin32Impl
 * Signature: (Ljava/awt/Window;F)V
 */
JNIEXPORT void JNICALL Java_org_noos_xing_mydoggy_plaf_ui_transparency_TransparencyManager_setAlphaModeRatioWin32Impl
  (JNIEnv *, jclass, jobject, jfloat);

#ifdef __cplusplus
}
#endif
#endif
