on:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        server-id: ossrh
        server-username: MAVEN_USERNAME
        server-password: MAVEN_PASSWORD
    - name: Publish package
      uses: coactions/setup-xvfb@v1
      with:
        run: mvn -B deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
    - name: Release Upload Assets
      uses: jaywcjlove/github-action-upload-assets@main
      if: steps.publish_package.outcome == 'success'
      with:
        asset-path: '["./mydoggy-api/target/*.jar", "./mydoggy-examples/target/*.jar", "./mydoggy-plaf/target/*.jar", "./mydoggy-res/target/*.jar", "./mydoggy-site-skin/target/*.jar"]'
